/**
 * Turn the raw capture output into typed source modules.
 *
 *   npm run gen
 *
 * Reads  tools/out/icons.json  +  tools/out/tables.json
 * Writes src/icons/lucide.ts   +  src/data/tables.ts
 *
 * These files are GENERATED — edit the capture pipeline, not the output.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(here, 'out');
const SRC = path.join(here, '..', 'src');

const banner = (from) =>
  `// GENERATED by tools/gen-assets.mjs from ${from} — do not edit by hand.\n` +
  `// Re-run \`npm run gen\` after a fresh capture.\n\n`;

/* ---- icons --------------------------------------------------------------- */
const iconsPath = path.join(OUT, 'icons.json');
if (!fs.existsSync(iconsPath)) {
  console.error('missing tools/out/icons.json — run `npm run capture` first');
  process.exit(1);
}
const icons = JSON.parse(fs.readFileSync(iconsPath, 'utf8'));

// Strip captured colour classes and fixed sizes so CSS drives both.
const norm = (s) => s
  .replace(/\sclass="[^"]*"/g, '')
  .replace(/\swidth="\d+"/, '')
  .replace(/\sheight="\d+"/, '')
  .replace(/\s+/g, ' ')
  .trim();

const byName = Object.fromEntries(
  Object.entries(icons.byName ?? {}).map(([k, v]) => [k, norm(v)]));
const leftRail = (icons.leftRail ?? []).map(norm);

fs.mkdirSync(path.join(SRC, 'icons'), { recursive: true });
fs.writeFileSync(path.join(SRC, 'icons', 'lucide.ts'),
  banner('the product\'s own DOM') +
  `/** Every lucide glyph the product ships, keyed by its own icon name. */\n` +
  `export const byName = ${JSON.stringify(byName, null, 2)} as const;\n\n` +
  `export type IconName = keyof typeof byName;\n\n` +
  `/** The 16 left module-rail icons, in on-screen order. */\n` +
  `export const leftRail: string[] = ${JSON.stringify(leftRail, null, 2)};\n\n` +
  `/** Look up a glyph by name, falling back to a supplied inline SVG. */\n` +
  `export const icon = (name: string, fallback = ''): string =>\n` +
  `  (byName as Record<string, string>)[name] ?? fallback;\n`);
console.log(`src/icons/lucide.ts   ${Object.keys(byName).length} glyphs, ${leftRail.length} rail icons`);

/* ---- tables -------------------------------------------------------------- */
const tablesPath = path.join(OUT, 'tables.json');
if (!fs.existsSync(tablesPath)) {
  console.error('missing tools/out/tables.json — run `npm run capture` first');
  process.exit(1);
}
const tables = JSON.parse(fs.readFileSync(tablesPath, 'utf8'));

/* The extractor also records per-cell colour/weight in `meta`. The app derives
   all of that from the value itself (severity, health, id pills), so drop it
   rather than shipping a second source of truth for styling. */
const slim = (t) => ({
  headers: t.headers,
  widths: t.widths,
  rows: t.rows.map((r) => ({ cols: r.cols })),
});
tables.vulnerabilities = slim(tables.vulnerabilities);
tables.endpoint = slim(tables.endpoint);

fs.mkdirSync(path.join(SRC, 'data'), { recursive: true });
fs.writeFileSync(path.join(SRC, 'data', 'tables.ts'),
  banner('the captured detail-page tabs') +
  `export interface TableModel {\n` +
  `  headers: string[];\n` +
  `  widths: number[];\n` +
  `  rows: { cols: string[] }[];\n` +
  `}\n\n` +
  `export const vulnerabilities: TableModel = ${JSON.stringify(tables.vulnerabilities, null, 1)};\n\n` +
  `export const endpoint: TableModel = ${JSON.stringify(tables.endpoint, null, 1)};\n`);
console.log(`src/data/tables.ts    vulnerabilities ${tables.vulnerabilities.rows.length} rows · ` +
            `endpoint ${tables.endpoint.rows.length} rows`);

/* ---- listing --------------------------------------------------------------- */
const listingPath = path.join(OUT, 'listing-model.json');
if (fs.existsSync(listingPath)) {
  const m = JSON.parse(fs.readFileSync(listingPath, 'utf8'));
  const keys = ['id', 'name', 'severity', 'exploitedCves', 'nonExploitedCves',
                'category', 'cvss', 'published', 'impactedEndpoints'];
  const records = m.rows.map((r) => Object.fromEntries(
    keys.map((k, i) => [k, r.cols[i] ?? ''])));

  fs.writeFileSync(path.join(SRC, 'data', 'listing.ts'),
    banner('the captured Vulnerability listing') +
    `export interface PatchRecord {\n${keys.map((k) => `  ${k}: string;`).join('\n')}\n}\n\n` +
    `/** Column labels exactly as the product renders them. */\n` +
    `export const columnLabels = ${JSON.stringify(m.headers, null, 2)} as const;\n\n` +
    `export const views = [\n  '${m.view}',\n] as const;\n\n` +
    `export const searchPlaceholder = ${JSON.stringify(m.searchPlaceholder)};\n\n` +
    `export const patches: PatchRecord[] = ${JSON.stringify(records, null, 1)};\n`);
  console.log(`src/data/listing.ts   ${records.length} patch records`);
} else {
  console.log('src/data/listing.ts   skipped — run `npm run capture:listing` first');
}
