// GENERATED by tools/gen-assets.mjs from the captured detail-page tabs — do not edit by hand.
// Re-run `npm run gen` after a fresh capture.

export interface TableModel {
  headers: string[];
  widths: number[];
  rows: { cols: string[] }[];
}

export const vulnerabilities: TableModel = {
 "headers": [
  "CVE ID",
  "Title",
  "Description",
  "Exploit Status",
  "Severity",
  "Status",
  "Vulnerability Type",
  "Patch Availability",
  "Impacted Endpoints"
 ],
 "widths": [
  175,
  164,
  332,
  120,
  86,
  85,
  148,
  142,
  158
 ],
 "rows": [
  {
   "cols": [
    "CVE-2026-48583",
    "secure@microsoft.com",
    "Use after free in Windows Kernel allows an authorized attacker to elevate privileges locally",
    "No",
    "High",
    "Analyzed",
    "OS",
    "Yes",
    "3"
   ]
  },
  {
   "cols": [
    "CVE-2026-48578",
    "secure@microsoft.com",
    "Protection mechanism failure in Windows Secure Boot allows an unauthorized attacker to bypass a security feature",
    "No",
    "High",
    "Analyzed",
    "OS",
    "Yes",
    "3"
   ]
  },
  {
   "cols": [
    "CVE-2026-48576",
    "secure@microsoft.com",
    "Protection mechanism failure in Windows Secure Boot allows an unauthorized attacker to bypass a security feature",
    "No",
    "High",
    "Analyzed",
    "OS",
    "Yes",
    "3"
   ]
  },
  {
   "cols": [
    "CVE-2026-48575",
    "secure@microsoft.com",
    "Protection mechanism failure in Windows Secure Boot allows an unauthorized attacker to bypass a security feature",
    "No",
    "High",
    "Analyzed",
    "OS",
    "Yes",
    "3"
   ]
  },
  {
   "cols": [
    "CVE-2026-48574",
    "secure@microsoft.com",
    "Heap-based buffer overflow in Windows Media allows an unauthorized attacker to execute code locally",
    "No",
    "High",
    "Analyzed",
    "OS",
    "Yes",
    "3"
   ]
  },
  {
   "cols": [
    "CVE-2026-48573",
    "secure@microsoft.com",
    "Protection mechanism failure in Windows Secure Boot allows an unauthorized attacker to bypass a security feature",
    "No",
    "High",
    "Analyzed",
    "OS",
    "Yes",
    "3"
   ]
  },
  {
   "cols": [
    "CVE-2026-48570",
    "secure@microsoft.com",
    "Protection mechanism failure in Windows Secure Boot allows an unauthorized attacker to bypass a security feature",
    "No",
    "High",
    "Analyzed",
    "OS",
    "Yes",
    "3"
   ]
  },
  {
   "cols": [
    "CVE-2026-48568",
    "secure@microsoft.com",
    "Protection mechanism failure in Windows Secure Boot allows an unauthorized attacker to bypass a security feature",
    "No",
    "High",
    "Analyzed",
    "OS",
    "Yes",
    "3"
   ]
  },
  {
   "cols": [
    "CVE-2026-48563",
    "secure@microsoft.com",
    "Heap-based buffer overflow in Remote Desktop Client allows an unauthorized attacker to execute code over a network",
    "No",
    "High",
    "Analyzed",
    "OS",
    "Yes",
    "3"
   ]
  },
  {
   "cols": [
    "CVE-2026-47656",
    "secure@microsoft.com",
    "Protection mechanism failure in Windows Boot Manager allows an unauthorized attacker to bypass a security feature",
    "No",
    "High",
    "Analyzed",
    "OS",
    "Yes",
    "3"
   ]
  },
  {
   "cols": [
    "CVE-2026-47652",
    "secure@microsoft.com",
    "Out-of-bounds read in Windows Hyper-V allows an unauthorized attacker to disclose information locally",
    "No",
    "High",
    "Analyzed",
    "OS",
    "Yes",
    "3"
   ]
  },
  {
   "cols": [
    "CVE-2026-47648",
    "secure@microsoft.com",
    "Untrusted search path in Windows Storage allows an authorized attacker to elevate privileges locally",
    "No",
    "High",
    "Analyzed",
    "OS",
    "Yes",
    "3"
   ]
  },
  {
   "cols": [
    "CVE-2026-47291",
    "secure@microsoft.com",
    "Integer overflow or wraparound in Windows HTTP.sys allows an unauthorized attacker to execute code over a network",
    "No",
    "Critical",
    "Analyzed",
    "OS",
    "Yes",
    "3"
   ]
  },
  {
   "cols": [
    "CVE-2026-45658",
    "secure@microsoft.com",
    "Protection mechanism failure in Windows BitLocker allows an unauthorized attacker to bypass a security feature",
    "No",
    "High",
    "Analyzed",
    "OS",
    "Yes",
    "3"
   ]
  },
  {
   "cols": [
    "CVE-2026-45657",
    "secure@microsoft.com",
    "Use after free in Windows Kernel allows an unauthorized attacker to elevate privileges locally",
    "No",
    "Critical",
    "Analyzed",
    "OS",
    "Yes",
    "3"
   ]
  }
 ]
};

export const endpoint: TableModel = {
 "headers": [
  "Agent ID",
  "Host Name",
  "IP Address",
  "Poller",
  "Agent Created By",
  "OS Name",
  "Version",
  "Service Pack",
  "Architecture",
  "Used By",
  "System Health"
 ],
 "widths": [
  108,
  153,
  112,
  73,
  144,
  192,
  81,
  115,
  111,
  152,
  124
 ],
 "rows": [
  {
   "cols": [
    "EP-380",
    "ACIWSUSV-01",
    "192.168.1.13",
    "",
    "Default",
    "Microsoft Windows 11 Pro",
    "8.7.301",
    "None",
    "64 BIT",
    "",
    "Healthy"
   ]
  },
  {
   "cols": [
    "EP-397",
    "Jevyjava-LT",
    "192.168.112.75",
    "",
    "",
    "Microsoft Windows 10 Enterprise",
    "8.7.404",
    "None",
    "64 BIT",
    "",
    "Healthy"
   ]
  },
  {
   "cols": [
    "EP-400",
    "PARTH-UPADHYAY",
    "192.168.1.75",
    "",
    "default",
    "Microsoft Windows 11 Pro",
    "8.6.300",
    "",
    "64 BIT",
    "",
    ""
   ]
  },
  {
   "cols": [
    "EP-396",
    "DESKTOP-A19KJ",
    "10.20.41.40",
    "",
    "Default",
    "Microsoft Windows 10 Pro",
    "8.7.200",
    "",
    "64 BIT",
    "",
    ""
   ]
  },
  {
   "cols": [
    "EP-392",
    "DHRUVPANCHAL",
    "10.20.40.202",
    "",
    "RW",
    "Microsoft Windows 11 Enterprise",
    "8.7.408",
    "None",
    "64 BIT",
    "",
    "Healthy"
   ]
  },
  {
   "cols": [
    "EP-391",
    "Adarsh-PC",
    "192.168.1.11",
    "",
    "Adarsh Fuinnc",
    "Microsoft Windows 10 Pro",
    "8.7.301",
    "None",
    "64 BIT",
    "",
    "Healthy"
   ]
  },
  {
   "cols": [
    "EP-389",
    "DESKTOP-N81KQ",
    "10.20.41.103",
    "",
    "Default",
    "Microsoft Windows 11 Pro",
    "8.7.301",
    "None",
    "64 BIT",
    "requester test",
    ""
   ]
  },
  {
   "cols": [
    "EP-388",
    "PARTH-UPADHYAY-2",
    "10.20.40.182",
    "",
    "Default",
    "Microsoft Windows 10 Enterprise",
    "8.7.301",
    "None",
    "64 BIT",
    "",
    "Healthy"
   ]
  },
  {
   "cols": [
    "EP-386",
    "DESKTOP-DK09P",
    "192.168.0.104",
    "",
    "Default",
    "Microsoft Windows 11 Pro",
    "8.7.301",
    "None",
    "64 BIT",
    "Chintan Makwana",
    "Healthy"
   ]
  },
  {
   "cols": [
    "EP-384",
    "ARJUN-CHAUHAN",
    "192.168.1.14",
    "",
    "arjun system",
    "Microsoft Windows 10 Pro",
    "8.7.301",
    "None",
    "64 BIT",
    "",
    ""
   ]
  },
  {
   "cols": [
    "EP-383",
    "DESKTOP-5F2AL",
    "192.168.29.101",
    "",
    "Default",
    "Microsoft Windows 11 Pro",
    "8.7.301",
    "None",
    "64 BIT",
    "",
    ""
   ]
  },
  {
   "cols": [
    "EP-382",
    "ACI10068-LP",
    "20.0.20.32",
    "",
    "Default",
    "Microsoft Windows 10 Enterprise",
    "8.7.301",
    "None",
    "64 BIT",
    "",
    ""
   ]
  },
  {
   "cols": [
    "EP-350",
    "DESKTOP-1P8YT",
    "192.168.177.20",
    "",
    "default",
    "Microsoft Windows 10 Pro",
    "8.6.101",
    "None",
    "64 BIT",
    "",
    ""
   ]
  },
  {
   "cols": [
    "EP-349",
    "DESKTOP-1KQZ9",
    "10.59.98.96",
    "",
    "default",
    "Microsoft Windows 11 Pro",
    "8.6.101",
    "None",
    "64 BIT",
    "",
    ""
   ]
  },
  {
   "cols": [
    "EP-501",
    "AHM-LT-0100",
    "10.20.30.20",
    "Default",
    "System",
    "Microsoft Windows 11 Pro",
    "8.7.301",
    "None",
    "64 BIT",
    "Priya Nair",
    "Critical"
   ]
  },
  {
   "cols": [
    "EP-502",
    "MUM-DT-0101",
    "10.21.31.21",
    "",
    "Default",
    "Microsoft Windows 10 Pro",
    "8.7.404",
    "None",
    "64 BIT",
    "",
    ""
   ]
  },
  {
   "cols": [
    "EP-503",
    "BLR-WS-0102",
    "10.22.32.22",
    "",
    "Default",
    "Microsoft Windows 11 Enterprise",
    "8.7.408",
    "None",
    "64 BIT",
    "",
    "Healthy"
   ]
  },
  {
   "cols": [
    "EP-504",
    "DEL-LT-0103",
    "10.23.33.23",
    "",
    "Default",
    "Microsoft Windows 10 Enterprise",
    "8.6.300",
    "None",
    "64 BIT",
    "Rahul Verma",
    ""
   ]
  },
  {
   "cols": [
    "EP-505",
    "PUN-DT-0104",
    "10.24.34.24",
    "Default",
    "Default",
    "Microsoft Windows Server 2019",
    "8.6.101",
    "None",
    "64 BIT",
    "",
    "Healthy"
   ]
  },
  {
   "cols": [
    "EP-506",
    "HYD-WS-0105",
    "10.25.35.25",
    "",
    "System",
    "Microsoft Windows Server 2022",
    "8.7.200",
    "None",
    "64 BIT",
    "",
    ""
   ]
  }
 ]
};
